Change the QuadraticModel Matrix constructor, add more tests
JuliaSmoothOptimizers/QuadraticModels.jl pull request #26
Opened 2020-10-01 10:26 UTC by geoffroyleconte

I finally changed the type of `H` in the default constructor to `SparseMatrixCSC{T, Int}`. I think the `tril!` function is mandatory because if the user inputs a `Symmetric{T, SparseMatrixCSC{I, Int}}` matrix, it is not possible to know if this matrix was constructed with a lower triangular matrix (maybe I am mistaken).

2020-10-01 12:18 UTC, abelsiqueira requested changes
Thanks, I made a few suggestions.

2020-10-01 12:18 UTC, abelsiqueira commented on test/problems/eqconqp.jl
> +  H    = Matrix(spdiagm(0 => 1.0:n))
Though I think it would be better that have a non-diagonal matrix here.

2020-10-01 12:18 UTC, abelsiqueira commented on test/problems/eqconqp.jl
> +  H    = Symmetric(spdiagm(0 => 1.0:n), :L)
Same here, non-symmetric would be better.

2020-10-01 13:24 UTC, geoffroyleconte commented on test/problems/eqconqp.jl
> +  H    = Matrix(spdiagm(0 => 1.0:n))
Thank you! I added `H[n,1 ] = 1.0`

2020-12-03 14:27 UTC, merged

2020-12-03 14:28 UTC, dpo commented
Sorry I lost track of this.