SlackModel for QuadraticModels
JuliaSmoothOptimizers/QuadraticModels.jl pull request #30
Opened 2021-01-20 20:54 UTC by geoffroyleconte

This allows to get H and A faster after using SlackModel. 
I modified qp.data, and created another meta using the code already written in NLPModels.slack_meta.

2021-01-20 23:22 UTC, dpo commented
Great, thank you. Do this work for you in RipQP?

When you've converged on the right design, it would be great to add a test.

2021-01-21 15:53 UTC, dpo commented
> Is it a problem if SlackModel changes its argument?

In what sense?

2021-01-21 16:06 UTC, geoffroyleconte commented
If the user wants to have the initial QuadraticModel and the QuadraticModel with the slack variables in two different objects.

2021-01-21 16:38 UTC, dpo commented
I think the user will often want to keep the original QP separate from the slack QP, so it's fine to copy data as you did.

However, for QPs, it could also be useful to write `SlackModel!`. I like the idea. Could you open an issue and open a separate PR?

2021-01-21 17:15 UTC, geoffroyleconte commented
I did not copy qp.data, I only copied qp.meta (I think). What about in this pull request? The two are similar. Or do you mean a pull request in NLPModels?

2021-01-21 17:57 UTC, dpo commented
I'm sorry. I didn't realize that you were modifying `qp.data` directly! I think what you implemented here is fine, but it doesn't match `NLPModels.SlackModel` (which doesn't modify the user's problem). You could call your method `SlackModel!` and only make it part of `QuadraticModels`. It would be great to add a few tests though to validate the slack model.

2021-01-26 21:49 UTC, dpo requested changes

2021-01-26 21:49 UTC, dpo commented on src/qpmodel.jl
> +  qp.data.Arows = [qp.data.Arows; qp.meta.jlow; qp.meta.jupp; qp.meta.jrng]
Est-ce qu'il n'y a pas moyen d'utiliser `append!()` ici pour ne pas dupliquer les données ?

2021-01-26 22:10 UTC, geoffroyleconte commented on src/qpmodel.jl
> +  qp.data.Arows = [qp.data.Arows; qp.meta.jlow; qp.meta.jupp; qp.meta.jrng]
Quelque chose comme cela?

2021-01-26 22:36 UTC, dpo commented on src/qpmodel.jl
> +  append!(qp.data.Avals, .-ones(T, ns))
Ici, je me demande si tu ne pourrais pas faire
```julia
append!(qp.data.Avals, (-one(T) for _ = 1 : ns))
```
pour éviter de construire un tableau de -1. Même chose à la ligne suivante.

2021-01-26 22:48 UTC, geoffroyleconte commented on src/qpmodel.jl
> +  append!(qp.data.Avals, .-ones(T, ns))
Oui, je savais pas qu'on pouvait faire ça, j'ai fait les changements

2021-01-27 00:18 UTC, merged

2021-01-27 00:18 UTC, dpo commented
Thank you! 🎉